#!/bin/sh
set -e

if [ "$1" = "configure" ] && which update-desktop-database >/dev/null 2>&1 ; then
        update-desktop-database -q
fi

if [ "$1" = "configure" ] && which gtk-update-icon-cache >/dev/null 2>&1 ; then
    gtk-update-icon-cache -q -f -t /usr/share/icons/hicolor
fi
